name: "Build"

run-name: "Build ${{ github.ref_name }}"

on:
  push:
    branches: [ main, java8 ]
  pull_request:
    branches: [ main, java8 ]
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    name: Build

    env:
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
      - name: Build
        run: make build
      - name: Test
        run: make test
